# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none # will disable CI builds entirely

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: .net Core Build Projects
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

# do this after other tasks such as building
- task: DotNetCoreCLI@2
  displayName: .net Core Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'


- task: NuGetCommand@2
  displayName: Nuget Pack SplishSplash.Backend.GpioService.Abstractions
  inputs:
    command: 'pack'
    packDestination: '$(Build.ArtifactStagingDirectory)/nuget/'
    packagesToPack: '/SplishSplash.Backend.GpioService.Abstractions/SplishSplash.Backend.GpioService.Abstractions.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: Nuget Pack SplishSplash.Backend.HubClientBackgroundService.Abstractions
  inputs:
    command: 'pack'
    packDestination: '$(Build.ArtifactStagingDirectory)/nuget/'
    packagesToPack: '/SplishSplash.Backend.HubClientBackgroundService.Abstractions/SplishSplash.Backend.HubClientBackgroundService.Abstractions.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: NuGet Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '56a906f6-92f1-4ea1-8474-dbd9bbad7ba0/d8ca8f72-a3c7-4dc5-aeed-8ac7e6f5a3fd'
    allowPackageConflicts: true

- task: DotNetCoreCLI@2
  displayName: .net Core Publish Linux-ARM
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--runtime linux-arm --self-contained false --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/arm'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName: .net Core Create Artifacts Linux-ARM
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/arm' 
    artifactName: 'splishsplashbackend-arm'

- task: DotNetCoreCLI@2
  displayName: .net Core Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--self-contained false --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/x86'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName: .net Core Create Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/x86' 
    artifactName: 'splishsplashbackend'