# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: .net Core Build Projects
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

# do this after other tasks such as building
- task: DotNetCoreCLI@2
  displayName: .net Core Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NuGetCommand@2
  displayName: .net Core Pack
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'

# The last task is a nuget command, nuget push
# This will push any .nupkg files to the 'TestFeed' artifact feed
# allowPackageConflicts allows us to build the same version and not throw an error when trying to push
# instead it just ingores the latest package unless the version changes
- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'SplishSplashFeed'
    versioningScheme: 'off'
    allowPackageConflicts: true

- task: DotNetCoreCLI@2
  displayName: .net Core Publish Linux-ARM
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--runtime linux-arm --self-contained false --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\arm'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName: .net Core Create Artifacts Linux-ARM
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\arm' 
    artifactName: 'splishsplashbackend-arm'

- task: DotNetCoreCLI@2
  displayName: .net Core Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--self-contained false --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\x86'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName: .net Core Create Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\x86' 
    artifactName: 'splishsplashbackend'