name: .NET Core

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/kleinrechner/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Install dependencies  
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Build and generate SplishSplash.Backend.HubClientBackendService.Abstractions NuGet package
      run: dotnet pack SplishSplash.Backend.HubClientBackendService.Abstractions/SplishSplash.Backend.HubClientBackgroundService.Abstractions.csproj --no-build --configuration Release --output out    
    
    - name: Build and generate SplishSplash.Backend.GpioService.Abstractions NuGet package
      run: dotnet pack SplishSplash.Backend.GpioService.Abstractions/SplishSplash.Backend.GpioService.Abstractions.csproj --no-build --configuration Release --output out
    
    - name: Build and generate SplishSplash.Backend.SettingsService.Abstractions NuGet package
      run: dotnet pack SplishSplash.Backend.SettingsService.Abstractions/SplishSplash.Backend.SettingsService.Abstractions.csproj --no-build --configuration Release --output out

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./splishsplash.backend/out/*.nupkg --skip-duplicate --no-symbols true
